---
title: "GR Analysis"
author: "Guo Xinyu"
date: "5/24/2017"
output: html_document
---

```{r, echo=TRUE}
library(xlsx)
library(RamiGO)
```

```{r, echo=TRUE}
test1<-read.csv(file="/Users/guoxinyu/Documents/USC/Final Thesis/stage 3/List1Panther.csv", header=TRUE, sep=",")
test<-as.data.frame(test1)
test<-test[,c(1,2,3)]
test$sampletotal<-49
test$reftotal<-20972
test<-test[,c(1,3,4,2,5)]

#Binomial text with Bonferroni procedure
BinomTest<-test
binfun <- function(x, y, z, n){binom.test(x, n, (y/z))}
result<-mapply(binfun, test$samplenum,test$refnum,test$reftotal,test$sampletotal)
myfun<- function(x){x$p.value}
pvalue<-apply(result,2,myfun)
BinomTest$Pvalue<-round(p.adjust(pvalue, method = "bonferroni"),digits=6)
ResultBinorm<-BinomTest[(round(p.adjust(pvalue, method = "bonferroni"),digits=6))<=0.05,]
ResultBinorm<-ResultBinorm[order(ResultBinorm$Pvalue),]
BinCheckGroup<-test1[(round(p.adjust(pvalue, method = "bonferroni"),digits=6))<=0.05,]


#Fisher exact test with FDR procedure
FisherTest<-test
FisherTest$samplenoobs<-FisherTest$sampletotal-FisherTest$samplenum
FisherTest$refnoobs<-FisherTest$reftotal-FisherTest$refnum
Testmod<-FisherTest[,c(2,6,4,7)]
rawp<-apply(Testmod,1,function(x) fisher.test(matrix(x,nr=2))$p.value)
FisherTest$FDR<-p.adjust(rawp, method = "BH")

ResultFisher<-FisherTest[(round(p.adjust(rawp, method = "fdr"),digits=6))<=0.1,]
ResultFisher<-ResultFisher[,c(1,2,4,6,7,8)]
ResultFisher<-ResultFisher[order(ResultFisher$FDR),]
nrow(ResultBinorm)
nrow(ResultFisher)
knitr::kable(ResultFisher)
knitr::kable(ResultBinorm)


FResultGonumber<-as.numeric(gsub("[^\\d]+", "", ResultFisher$Go, perl=TRUE))
BResultGonumber<-as.numeric(gsub("[^\\d]+", "", ResultBinorm$Go, perl=TRUE))
intersect(FResultGonumber,BResultGonumber)
setdiff(BResultGonumber,intersect(FResultGonumber,BResultGonumber))



test2<-read.csv(file="/Users/guoxinyu/Documents/USC/Final Thesis/stage 3/List2Panther.csv", header=TRUE, sep=",")
test<-as.data.frame(test2)
test<-test[,c(1,2,3)]
test$sampletotal<-90
test$reftotal<-20972
test<-test[,c(1,3,4,2,5)]

BinomTest<-test
binfun <- function(x, y, z, n){binom.test(x, n, (y/z))}
result<-mapply(binfun, test$samplenum,test$refnum,test$reftotal,test$sampletotal)
myfun<- function(x){x$p.value}
pvalue<-apply(result,2,myfun)
BinomTest$Pvalue<-round(p.adjust(pvalue, method = "bonferroni"),digits=6)
ResultBinorm1<-BinomTest[(round(p.adjust(pvalue, method = "bonferroni"),digits=6))<=0.05,]
ResultBinorm1<-ResultBinorm1[order(ResultBinorm1$Pvalue),]
BinCheckGroup1<-test2[(round(p.adjust(pvalue, method = "bonferroni"),digits=6))<=0.05,]





#Fisher exact test with FDR procedure
FisherTest<-test
FisherTest$samplenoobs<-FisherTest$sampletotal-FisherTest$samplenum
FisherTest$refnoobs<-FisherTest$reftotal-FisherTest$refnum
Testmod<-FisherTest[,c(2,6,4,7)]
rawp<-apply(Testmod,1,function(x) fisher.test(matrix(x,nr=2))$p.value)
FisherTest$FDR<-p.adjust(rawp, method = "BH")

ResultFisher1<-FisherTest[(round(p.adjust(rawp, method = "fdr"),digits=6))<=0.1,]
ResultFisher1<-ResultFisher1[,c(1,2,4,6,7,8)]
ResultFisher1<-ResultFisher1[order(ResultFisher1$FDR),]
nrow(ResultBinorm1)
nrow(ResultFisher1)

knitr::kable(ResultFisher1)
knitr::kable(ResultBinorm1)


FResultGonumber<-as.numeric(gsub("[^\\d]+", "", ResultFisher1$Go, perl=TRUE))
BResultGonumber<-as.numeric(gsub("[^\\d]+", "", ResultBinorm1$Go, perl=TRUE))
intersect(FResultGonumber,BResultGonumber)
setdiff(BResultGonumber,intersect(FResultGonumber,BResultGonumber))

goIDs<-gsub("(?<=\\()[^()]*(?=\\))(*SKIP)(*F)|.", "", ResultFisher$Go, perl=T)
goIDs1<-gsub("(?<=\\()[^()]*(?=\\))(*SKIP)(*F)|.", "", ResultFisher1$Go, perl=T)
intersect(goIDs1,goIDs)
goIDinter<-intersect(goIDs1,goIDs)
length(goIDinter)


xlsx<-read.xlsx2("/Users/guoxinyu/Documents/USC/Final Thesis/stage 3/nature10251-s2.xls", 2)
GoIDExcel<-as.character(xlsx$Term.ID[xlsx$Term.ID!=""])
intersect(GoIDExcel,goIDinter)
intersect(GoIDExcel,goIDs1)
intersect(GoIDExcel,goIDs)
length(intersect(GoIDExcel,goIDinter))


#pvalues<-rep(0.0001, length(goIDinter))
#pngRes <- getAmigoTree(goIDs=goIDinter, pvalues=pvalues, pcolors = c("white","tomato"),psplit = c(1,0.25,0.1,0.05,0.001), filename="/Amigo for intersection of List1 and List 2", picType="png", saveResult=TRUE)

```
